server:
  port: 9000

security:
  jwt:
    key-store: classpath:mykeystore.jks
    key-store-password: qweqwe
    key-pair-alias: servercert
    key-pair-password: qweqwe

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.64.2.197:3306/TESTDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mariadb
    password: user602
  jackson:
    serialization:
      INDENT_OUTPUT: true