server:
  port: 5611
  
ecb-service: http://10.96.2.230:8080/ecplibjsf/

security:
  jwt:
    key-store: classpath:mykeystore.jks
    key-store-password: qweqwe
    key-pair-alias: servercert
    key-pair-password: qweqwe

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.96.2.230:3306/bibl?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
logging:
  file: C:/logs/dev_app_reg.log
  pattern:    
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    kz.ktzh: DEBUG
    org.hibernate: DEBUG