server:
  port: 9100  

security:
  jwt:
    public-key: classpath:public.txt

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.64.2.197:3306/TESTDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mariadb
    password: user602
  jackson:
    serialization:
      INDENT_OUTPUT: true