server:
  port: 9100  

security:
  jwt:
    public-key: classpath:public.txt

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    sqlScriptEncoding: UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.111:3306/bibl?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    serialization:
      INDENT_OUTPUT: true
logging:
  file: C:/logs/dev_app.log
  pattern:    
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    kz.ktzh: DEBUG
    org.hibernate: DEBUG